### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by krsna1729** [omec-project/openmme#1]
- [ ] Use markdown [guide](https://guides.github.com/features/mastering-markdown/) to make README render better
- [ ] Use 1 line repo description. Currently its a lengthy duplicate of what exists in the README
- [ ] Create a table of contents [TOC ](https://ecotrust-canada.github.io/markdown-toc/)
- [ ] #5 Install steps for freeDiameter OR `git clone --recursive url` with `.gitmodules`

**Comment by thakurajayL** [comment]
anyone working on it ? else i would like to move current ReadMe to markdown file.
Please assign it to me if you agree

**Comment by krsna1729** [comment]
@pingping-lin

**Comment by ghost** [comment]
I do not anyone work on it, please go ahead @thakurajayL

**Comment by krsna1729** [comment]
@pingping-lin can you assign?

**Comment by ghost** [comment]
[image: image.png]

is this ok?
