### ISSUE TITLE
Test Multiple eNB connection to MME

### ISSUE THREAD

**Issue by thakurajayL** [omec-project/openmme#26]
Please confirm if MME code can handle multiple eNB connections.

**Comment by vbarate** [comment]
MME is tested with 2 eNB connections.
Code supports multiple eNB connections, due to setup limitations could not test more. Please go ahead with the test if the setup is available.

**Comment by thakurajayL** [comment]
This works and we had issues in the SCTP connection closure. When MME sees socket connection is closed then it was causing crash in the MME. Fixed the crash in the MME>
